# Generated by Django 3.0.8 on 2020-07-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=200)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('xlsx', models.FileField(upload_to='files/xlsx/')),
            ],
        ),
    ]
